### ISSUE TITLE
Demo run with failure

### ISSUE THREAD

**Issue by JohnJGL** [vimeo/VimeoUpload#102]
#### Issue Summary

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

after pod install, it shows the error below:
[!] Error installing VimeoNetworking
[!] /usr/bin/git clone git@github.com:vimeo/VimeoNetworking.git /var/folders/38/jlhr8mdj7gjb452xbh_qvz2c0000gp/T/d20160624-27718-1wf33rj --template= --single-branch --depth 1 --branch master

Cloning into '/var/folders/38/jlhr8mdj7gjb452xbh_qvz2c0000gp/T/d20160624-27718-1wf33rj'...
Warning: Permanently added the RSA host key for IP address '192.30.252.122' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
#### Reproduction Steps

Download the demo and run

**Comment by ankurmahesh** [comment]
When I had this error, I followed the steps on this page to fix it: https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

**Comment by alfiehanssen** [comment]
@JohnJGL We just fixed a host of issues with the example projects today. They should be good to go now. Let us know if you have questions or see otherwise.
