### ISSUE TITLE
AuthenticationController.clientCredentialGrant does not have a VIMUser associated with the VIMAccount.

### ISSUE THREAD

**Issue by mrdavidrees** [vimeo/VimeoUpload#104]
#### Issue Summary
AuthenticationController.clientCredentialGrant does not have a VIMUser associated with the VIMAccount.

I'm pretty confident that this isn't an actual issue with your library but I'm raising a ticket as I there is no resources addressing this.

### The Goal.
Let users upload videos to our account, currently a Vimeo Plus account, but will be upgraded to Pro before release. These videos will be accessible throughout out app to any users of our app.

### Version
    pod 'VimeoUpload', :git => 'https://github.com/vimeo/VimeoUpload.git', :branch => 'CAM-354'
    pod 'VimeoNetworking', :git => 'https://github.com/vimeo/VimeoNetworking.git', :branch => 'cameo'
I cant use the master branch because of this issue:
[https://github.com/vimeo/VimeoNetworking/issues/34](url)
Which although is fixed, still causes me issues.

### Details

Currently within the VimeoUploadFramework the only publicly accessible api for creating a video on the Vimeo servers is the PHAssetCloudExportQuotaCreateOperation(me: user, phAsset: asset, sessionManager: session), this takes a user and a session. Unfortunately when we request authorization we never receive a User and therefore can never upload

This is the request authorization code used:

    class Vimeo: VimeoUploader<UploadDescriptor>
    {
        static let BackgroundIdentifier = "com.vimeo.upload"
        static let sharedInstance = Vimeo(backgroundSessionIdentifier: BackgroundIdentifier, descriptorManagerDelegate: nil) {
            return ApiKeys.VimeoUpload
        }
        
        var session: VimeoSessionManager?
        var user: VIMUser?
        
        override init(backgroundSessionIdentifier: String, descriptorManagerDelegate: DescriptorManagerDelegate?, accessTokenProvider: VimeoRequestSerializer.AccessTokenProvider) {
            super.init(backgroundSessionIdentifier: backgroundSessionIdentifier, descriptorManagerDelegate: descriptorManagerDelegate, accessTokenProvider: accessTokenProvider)
        }
        
        func authenticate(completion: (user: VIMUser?)->Void ){
            if let user = self.user  {
                completion(user: user)
            }
            
            let scopes = [Scope.Private, Scope.Public, Scope.Create, Scope.Upload]
            let config = AppConfiguration(clientIdentifier: "xxx", clientSecret: "xx/xxx/xx", scopes: scopes)
            let client = VimeoClient(appConfiguration: config)
            session = VimeoSessionManager.backgroundSessionManager(identifier: self.dynamicType.BackgroundIdentifier, appConfiguration: config)
            
            
            let authentication = AuthenticationController(client: client)
            authentication.clientCredentialsGrant { (result) in
                
                switch result {
                case .Failure(let error):
                    print(error)
                    
                case.Success(let client):
                    print(client)
                    if client.isAuthenticated() {
                        self.user = client.user
                    }
                }
                completion(user: self.user)
                
            }
        }
    }

### The Question.
Am I supposed to use PHAssetCloudExportQuotaCreateOperation?
Is there anything wrong with our set up?
Am I using the incorrect branch?

Thanks, David.

**Comment by mrdavidrees** [comment]
@alfiehanssen Any chance you can give a quick pointer of what to do, where to go?

**Comment by alfiehanssen** [comment]
@mrdavidrees Apologies for the delay, 

This is actually expected behavior, the "client credentials grant" does not return a user object. It only returns an account object (token etc). This is because "client credentials" is essentially the mechanism to obtain an auth token as a "logged out" user. It will let you access all public info in the Vimeo ecosystem, but no private user-specific information. It's like browsing the Vimeo iOS app or website while logged out. 

You'll only get a user object when you actually log in as a user. This is what you want to do. There are a few ways to log a user in:

1. Use the "code grant" approach to authentication. This is the flow where the user of your app is bounced to Safari, asked to log in, and then is bounced back to your app and you are passed the authenticated account+user object.

2. Obtain a user auth token from developer.vimeo.com and embed this token in your application. Use it to sign all of your requests. 

It sounds like option 2 is what you want. If you want all users of your app to upload to the same account (your account). Make sense?

Let us know if you have questions, 

Alfie

**Comment by mrdavidrees** [comment]
Ok thankyou, I've finally figured out exactly how to upload, I didn't realise the a VimeoUpload had its own foreground session and that I could request my user data with meDataTask. Thanks for your direction. I'm going to leave this code here as some form guidance on how to at least get started uploading videos with a user auth token, as I cannot find any examples of this anywhere.


    class NewVimeoUploader: VimeoUploader<UploadDescriptor> {
        
        static let BackgroundIdentifier = "com.vimeo.upload"
        
        static let sharedInstance = NewVimeoUploader(backgroundSessionIdentifier: BackgroundIdentifier, descriptorManagerDelegate: nil)
        {
            return "YOUR_PERSONAL_ACCESS_TOKEN"
        }
        
        override init(backgroundSessionIdentifier: String, descriptorManagerDelegate: DescriptorManagerDelegate?, accessTokenProvider: VimeoRequestSerializer.AccessTokenProvider)
        {
            super.init(backgroundSessionIdentifier: backgroundSessionIdentifier, descriptorManagerDelegate: descriptorManagerDelegate, accessTokenProvider: accessTokenProvider)
        }
        
        
        func uploadAsset(asset: PHAsset)
        {
            let task = try! foregroundSessionManager.meDataTask { [weak self] (user, error) -> Void in
                
                guard let strongSelf = self else
                {
                    return
                }
                
                guard let user = user else
                {
                    return
                }
                
                let operation = PHAssetCloudExportQuotaCreateOperation(me: user, phAsset: asset, sessionManager: self.foregroundSessionManager)
                
                operation.videoSettings = VideoSettings(title: "Title", description: "Description", privacy: VIMPrivacy_Private, users: nil, password: nil)
                
                operation.completionBlock = { () -> Void in
                    
                    guard let url = operation.url else
                    {
                        return
                    }
                    
                    guard let uploadTicket = operation.uploadTicket else
                    {
                        return
                    }
                    
                    let descriptor = UploadDescriptor(url: url, uploadTicket: uploadTicket)
                    
                    descriptor.identifier = asset.localIdentifier
                    
                    self.uploadVideo(descriptor: descriptor)
                    
                }
                
                operation.downloadProgressBlock = { (progress: Double) -> Void in
                    print(String(format: "Download progress: %.2f", progress))
                }
                
                operation.exportProgressBlock = { (progress: Double) -> Void in
                    print(String(format: "Export progress: %.2f", progress))
                }
                
                operation.start()
            }
            
            task.resume()
        }
    }

In the spirit of things I've tried to make sure I conform to your meticulously explicit programming style

**Comment by ankurmahesh** [comment]
@mrdavidrees 

Thanks so much for code.  I added it to my project, but the video never uploads.  Xcode's logs just say "Create (phAsset identifier)"  I tried to follow the README on this library, but I was still running into problems.  Would you be able to help me out?  https://github.com/vimeo/VimeoUpload/issues/107
