### ISSUE TITLE
Can't find "VIMThumbnailUploadTicket" class.

### ISSUE THREAD

**Issue by mdhaider1811** [vimeo/VimeoUpload#115]
#### Issue Summary

A class "VIMThumbnailUploadTicket" is used by two classes "VimeoResponseSerializer+Thumbnail.swift" and "CAMUploadDescriptor.swift" on following lines:

VimeoResponseSerializer+Thumbnail.swift : 14, 29, 100 and 105
CAMUploadDescriptor.swift : 20
#### Reproduction Steps

Unable to use VimeoUpload framework code with Objective-C suing Xcode 8.0
#### Expected Behavior

What do you expect to happen as a result of the reproduction steps?
There should be class named "VIMThumbnailUploadTicket".
#### Actual Behavior

What currently happens as a result of the reproduction steps?
No "VIMThumbnailUploadTicket" present, so unable to use VimeoUpload framework.

[Archive.zip](https://github.com/vimeo/VimeoUpload/files/504670/Archive.zip)

Please try to add this file ASAP.

Thanks!!!

**Comment by alfiehanssen** [comment]
@mikew-personal Can you speak to this issue?

**Comment by rpassis** [comment]
This should be fixed in more recent versions of the library. 

Please feel free to comment on this issue if you are still having problems.
