### ISSUE TITLE
1.0 release?

### ISSUE THREAD

**Issue by appcelerate** [vimeo/VimeoUpload#124]
Hi I wanted to know when u are releasing the 1.0 version because in your post from stackoverflow:
http://stackoverflow.com/questions/38339748/how-to-use-vimeo-upload

you wrote in august it will be a cocoa pods version available. 

Would be perfect to know when this version will come live :)

Regards

**Comment by eikaiwason** [comment]
Any update on this?  Will it be updated to Swift 3?
