### ISSUE TITLE
Not Able to Upload Video

### ISSUE THREAD

**Issue by ErAshu** [vimeo/VimeoUpload#149]
While i am uploading video through this example, i am getting `fatal error: unexpectedly found nil while unwrapping an Optional value`

I am attaching screenshot. 
![screen shot 2017-07-28 at 2 12 39 pm](https://user-images.githubusercontent.com/4178384/28709723-0fb5d42e-739f-11e7-8f58-467e217c8f6f.png)

I am only passing **OAUTH_TOKEN** getting from https://developer.vimeo.com/apps. 
![screen shot 2017-07-28 at 2 17 54 pm](https://user-images.githubusercontent.com/4178384/28709871-a6b17590-739f-11e7-8fb2-b84ddf1b1b83.png)

See My code here
![screen shot 2017-07-28 at 2](https://user-images.githubusercontent.com/4178384/28709889-b86c7992-739f-11e7-9f02-c735ad265a75.png)

I am able to see all my videos but not able to upload.

**Please help me.**

**Comment by supperspidey** [comment]
Hello @ErAshu ,

Thank you for your patience. We've just released a fix for this unsafe optional unwrapping in `develop` branch. Basically the reason why the video object attached to the upload ticket is `nil` from the beginning is because the [two-step or new upload flow is not available for third-party apps yet](https://github.com/vimeo/VimeoUpload#old-upload-new-upload). You can still try out the four-step or old upload API though. To do that, you'll need to switch the build target to `VimeoUpload-iOS-OldUpload` then build it with your Vimeo auth token.

Please let us know if you encounter any issue with the old upload API. We look forward to hearing from you.

**Comment by ErAshu** [comment]
@supperspidey Thanks for your kind reply. Now i can upload video through `VimeoUpload-iOS-OldUpload` but a issue is there, when i see my my https://vimeo.com/home/myvideos/page:1/sort:date/format:video Page, i can see the uploaded video but doesn't access by without login. Screenshot attached. Video url https://vimeo.com/230274664
It will very helpful if user gets the uploaded url and can see from any browser.

Please help.
![screen shot 2017-08-19 at 9 51 35 pm](https://user-images.githubusercontent.com/4178384/29488456-2cd276ac-8529-11e7-90c9-a96765126787.png)

**Comment by supperspidey** [comment]
Hello @ErAshu ,

For the old upload flow, we hard-coded the privacy setting to `nobody` in `VideoSettingsViewController`, which means nobody will have access to the video.

![screen shot 2017-08-21 at 10 42 41 am](https://user-images.githubusercontent.com/2098675/29524332-90b90a8e-865d-11e7-93fa-35f91ad98625.png)

If you want to change the privacy setting, you can use the constants that we have declared in `VIMPrivacy.h`:

- `VIMPrivacy_Private`: limited to the only user who posted the video; this is the behavior that you might have observed.
- `VIMPrivacy_Select`: limited to selected users; for this to work, you'll need to pass in an array of user ID's into the `VideoSettings`'s constructor.
- `VIMPrivacy_Password`: limited to the users with password that you set for the video; for this to work, you'll need to pass in a password string into the `VideoSettings`'s constructor.
- `VIMPrivacy_Following`: limited to the users that you follow
- `VIMPrivacy_Public`: Everyone will be able to see the uploaded video.

**Comment by ErAshu** [comment]
Thanks @supperspidey . Now i am able to upload with Public privacy. 
From where i can get the upload url, so that send it to my server. I need url like https://vimeo.com/xxxxxxxxx

Thanks!!!

**Comment by supperspidey** [comment]
Hello @ErAshu ,

For the `VimeoUpload` framework we use a data structure called "descriptor" &mdash; in the case of OldUpload flow, it is of type `OldUploadDescriptor` &mdash; to upload a video. The descriptor knows everything about the uploaded video, from the upload's progress to the video's URI. When the upload is finished, you can try accessing the URI via the descriptor. Constructing the video's URL from its URI is trivial &mdash; you just need to concatenate `www.vimeo.com` at the front.

**Comment by nicolelehrer** [comment]
@ErAshu to build off of @supperspidey's response you can get the uri from the descriptor but it depends when you try to access it. Check out these steps to get the constructed video URL and let us know if that helps: 

- make sure project target `VimeoUpload-iOS-OldUpload` is selected

- set a breakpoint at this line: `self.video = try responseSerializer.process(videoSettingsResponse: task.response, url: url, error: error)`

- the above line can be found inside of class `OldUploadDescriptor`, inside method `func taskDidFinishDownloading(sessionManager: AFURLSessionManager, task: URLSessionDownloadTask, url: URL) -> URL?`, under the case handling for `.Settings`

- To obtain the url of the video, access the link property on the video object, i.e. `self.video?.link`
