### ISSUE TITLE
Compiler Errors

### ISSUE THREAD

**Issue by skyrillos** [vimeo/VimeoUpload#176]
I am currently receiving multiple compiler errors with VimeoUpload. I already followed the instructions on using VimeoNetworking and VimeoUpload as submodules. 

I also tried to add VimeoNetworking and VimeoUpload in a new/empty project, I am still having the same issue.

Can anyone point me to a fix/solution? Thanks!

![screen shot 2018-07-04 at 7 27 02 pm](https://user-images.githubusercontent.com/6846420/42274778-81b29444-7fc0-11e8-9b85-abfd7300a4b6.png)

**Comment by skyrillos** [comment]
Thanks for the reply @jasonhawkins,

Sorry I forgot to include the Swift version were using, we are currently using Swift 4.1

I added the code in the project's Podfile and it gave me new compiler errors. Here's the screenshot.

<img width="208" alt="screen shot 2018-07-06 at 10 10 11 am" src="https://user-images.githubusercontent.com/6846420/42356395-d241f400-8104-11e8-827c-45554b334281.png">

I tried to check the error with _VimeoSessionManager.backgroundSessionManager_, it seems that the method has a different set of parameters. What's the supported version for VimeoNetworking when using VimeoUpload?

Here's what we're currently using
VimeoNetworking (3.1.0)
VimeoUpload (1.0.2)

Thanks!

**Comment by patriksharma** [comment]
@jasonhawkins  never mind,  made it worked. 

 ```
static let sharedInstance = NewVimeoUploader(backgroundSessionIdentifier: "com.XX.XXX", descriptorManagerDelegate: nil, accessTokenProvider: { () -> String? in
        return "XXXXXX"
    }, apiVersion: APIVersionString)

    
  override   init(backgroundSessionIdentifier: String, descriptorManagerDelegate: DescriptorManagerDelegate?, accessTokenProvider: @escaping VimeoRequestSerializer.AccessTokenProvider, apiVersion: String) {
        super.init(backgroundSessionIdentifier: backgroundSessionIdentifier, accessTokenProvider: accessTokenProvider, apiVersion: NewVimeoUploader.APIVersionString)
    }
```

**Comment by patriksharma** [comment]
@jasonhawkins  how to show progress upload ? I can see export block running but progress upload doesn't show up  ? any idea ?

**Comment by supperspidey** [comment]
Hello @patriksharma . Can you please create a separate issue regarding upload progress so that I can better help you? Thank you!

**Comment by patriksharma** [comment]
@supperspidey  Sure, will do that

**Comment by jasonhawkins** [comment]
@skyrillos I'm going to go ahead and close out this issue, but let us know if you have any more questions 🚀

**Comment by skyrillos** [comment]
@jasonhawkins Thanks for the responses!

Decided to move on to another module for our app. Will try out the above mentioned solutions when I go back with uploading and as soon as a I am done with the other modules.
