### ISSUE TITLE
This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique

### ISSUE THREAD

**Issue by patriksharma** [vimeo/VimeoUpload#177]
**This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique**

I tried running your sample code. I have changed the bundle identifier as well as token. but everytime i run the app < i get above warning. Not sure what's wrong. 

```

static let sharedInstance = NewVimeoUploader(backgroundSessionIdentifier: "com.xxx.xxx") { () -> String? in
        return "XXXXXXXXXXXXXXXXXXXXX197" // See README for details on how to obtain and OAuth token
    }
```

**Comment by supperspidey** [comment]
Hello @patriksharma ! It looks like you are using `NewVimeoUploader`, which uses a private API endpoint. That means even if you can run `VimeoUpload-iOS` scheme, you will not be able to upload a video. Were you able to run the `VimeoUpload-iOS-OldUpload` scheme?

**Comment by patriksharma** [comment]
@supperspidey  Yeah I used newVimeoUploader. Basically I did Pod install which was a tough task at the moment :). I managed to upload video using `vimeoupload-IOS` 

old upload scheme was showing error in swift 4.1 and I was unable to use it. So I decided to go with developer branch. Everything works fine now. Videos are showing up in vimeo account.

**Comment by supperspidey** [comment]
@patriksharma super! I'm glad that `VimeoUpload-iOS` scheme works for you.

It turns out that from the API side, the private API endpoint has become public, but we haven't made an official release for VimeoUpload to reflect that. If you point to `develop`, you can take advantage of the new API however.

**Comment by patriksharma** [comment]
Correct Code : Tested and works for Swift 4.1 . Closing issue
```

 static let sharedInstance = NewVimeoUploader(backgroundSessionIdentifier: "com.XXX.XXX", descriptorManagerDelegate: nil, accessTokenProvider: { () -> String? in
        return "XXXXX"
    }, apiVersion: APIVersionString)

```
