### ISSUE TITLE
How to Show Progress Block of video upload

### ISSUE THREAD

**Issue by patriksharma** [vimeo/VimeoUpload#179]
#### Issue Summary
A brief but thorough description of the issue.

#### Reproduction Steps
Detailed steps to reproduce the issue.

#### Expected Behavior
What do you expect to happen as a result of the reproduction steps?

#### Actual Behavior
What currently happens as a result of the reproduction steps?

**Comment by supperspidey** [comment]
@patriksharma are you using `UploadDescriptor`? If so, then you can try observing either its `Progress` or `progressObservable` property via KVO.

**Comment by patriksharma** [comment]
@supperspidey  I checked your demo app as well as I tried using it but it never gets called. it was written  inside `Self.setupAndStartOperation()`

```
 operation.downloadProgressBlock = { (progress: Double) -> Void in
            print(String(format: "Download progress: %.2f", progress)) // TODO: Dispatch to main thread
            }
```

**Comment by patriksharma** [comment]
```
 operation.exportProgressBlock = { (exportSession: AVAssetExportSession, progress: Double) -> Void in
            print(String(format: "Export progress: %.2f", progress))
        }
```

This block gets called and I get Video URL from `uploadDescriptor`

**Comment by supperspidey** [comment]
Oh I see. Are you trying to observe the asset downloading and exporting progresses?

**Comment by patriksharma** [comment]
yeah correct.
