### ISSUE TITLE
background upload is not working for Large videos ( for example .< 500MB)

### ISSUE THREAD

**Issue by patriksharma** [vimeo/VimeoUpload#182]
#### Issue Summary
A brief but thorough description of the issue.

#### Reproduction Steps
Detailed steps to reproduce the issue.

#### Expected Behavior
What do you expect to happen as a result of the reproduction steps?

#### Actual Behavior
What currently happens as a result of the reproduction steps?

**Comment by patriksharma** [comment]
Well I achieved uploading videos to vimeo server using `developer branch` vimeo API. 
when I put app in background for large videos, it stops uploading the progress. 

`self.operation?.start()` - this function start your uploading progress.
Here is the parent class for `self.operation -   ExportSessionExportCreateVideoOperation` and `operation`

==========
if I give you example how I was expecting this to work. I have used `alamofire` library for background upload of video. we create a backgrouns session manager class. It calls when upload is finished and completion handler generate a local notification of video upload. 

```
class BackendAPIManager: NSObject {
    static let sharedInstance = BackendAPIManager()
    
    var alamoFireManager : Alamofire.SessionManager!
    
    var backgroundCompletionHandler: (() -> Void)? {
        get {
            return alamoFireManager?.backgroundCompletionHandler
        }
        set {
            alamoFireManager?.backgroundCompletionHandler = newValue
        }
    }
    
    fileprivate override init()
    {
        let configuration = URLSessionConfiguration.background(withIdentifier: "com.url.background")
        configuration.timeoutIntervalForRequest = 200 // seconds
        configuration.timeoutIntervalForResource = 200
        self.alamoFireManager = Alamofire.SessionManager(configuration: configuration)
    }
}

```

**Comment by patriksharma** [comment]
@supperspidey  something similar can we achieve here too.

**Comment by supperspidey** [comment]
Hi @patriksharma . Per our discussion in the previous Github issue, `ExportSessionExportCreateVideoOperation` is the operation class used to download and copy a selected video to your app's sandbox. During the execution of this operation, the actual upload operation has not started yet.

For your case, it was possible that for small videos, the export session could complete quickly, so upload was able to begin in the foreground. For big videos however, exporting could be slow, so when you backgrounded your app, the export session was not able to complete on time (keep in mind that `AVExportSession` does not support background.) That might explain why big videos did not upload in the background for your app.

Did you try waiting for export session to complete before backgrounding the app?

If your videos are of fixed, reasonable size, one way to keep the app in the foreground a bit longer is to use the following `ProcessInfo` method:
```
func performExpiringActivity(withReason reason: String, using block: @escaping (Bool) -> Void)
```
In the block, you can try keeping the export session working, and see if it can finish the operation, but your mileage might vary.

Please let me know if my suggestion works.

**Comment by supperspidey** [comment]
Hi @patriksharma ! I hope my answer can help you with your problem. Is it okay if I close your issue?

**Comment by patriksharma** [comment]
yes, that explanation resolved my query
