### ISSUE TITLE
uploading video from SDK shows extra feature in web Version Like Share, More from user etc

### ISSUE THREAD

**Issue by patriksharma** [vimeo/VimeoUpload#185]
Hello,

I'm uploading videom from SDK and it uploaded successfully. 

When I view it in web its shows me extra features in the video which is not required to show to user. Is there any settings i can add to avoid

1) After screen - More videos content
2) Like and share button - Hide 

![screen shot 2018-08-09 at 10 29 14 am](https://user-images.githubusercontent.com/383524/43878976-611bec24-9bbf-11e8-87f1-b8cc275815a8.png)

**Comment by supperspidey** [comment]
Hi @patriksharma ! My apology for replying back to you this late. I believe you can customize the embedded player's UI, but only if the account is either `Business`, `PRO`, or `Plus`:

https://help.vimeo.com/hc/en-us/articles/224972808-Customizing-the-embedded-player

I hope that answers your question.

**Comment by patriksharma** [comment]
thanks @supperspidey  for info

**Comment by supperspidey** [comment]
Hello @patriksharma . `VimeoUpload` can only transfer video files from one's device to our Vimeo server, so as far as I know, the library doesn't provide customization for embedded players; however, you can fork the repo and provide your own customization to network requests as `VimeoUpload` is open-sourced.

I've also found a Vimeo API link that might be useful for you:
https://developer.vimeo.com/player/sdk/embed

**Comment by supperspidey** [comment]
@patriksharma I'll close this issue for now, but if you have any question, please let us know.
