### ISSUE TITLE
vimeo api v3.4 now requires "upload.approach" instead of "type" for POST https://api.vimeo.com/me/videos

### ISSUE THREAD

**Issue by ladeiko** [vimeo/VimeoUpload#194]
#### Issue Summary

vimeo api v3.4 now requires "upload.approach" instead of "type" for POST https://api.vimeo.com/me/videos

#### Reproduction Steps
Try to upload video

#### Expected Behavior
Upload succeeded

#### Actual Behavior
Vimeo API return 502 with Error Code: 3116

**Comment by nicolelehrer** [comment]
Hi @ladeiko - check out our example project for the target `VimeoUpload-iOS` on `master`. It's configured to use API v3.4, and it handles formatting that request in `createVideoRequest`. Let us know if you still have any issues.
