### ISSUE TITLE
Compiler Errors

### ISSUE THREAD

**Issue by swissdude** [vimeo/VimeoUpload#221]
I included the VimeoUploader into my project using cocoapods as described (using submodules).

When trying to compile my app, the compiler throws several errors (see attached image).

I'm using Xcode 10.2.1, Swift Language Version is set to 4.2

(I tried to get an answer on Stackoverflow, but the question was closed due to being «off topic». The user @Rog suggested to open an issue here).

<img width="424" alt="Bildschirmfoto 2019-06-08 um 16 44 08" src="https://user-images.githubusercontent.com/2203969/59148714-ab518d80-8a0c-11e9-8218-93eb3ca88de2.png">

**Comment by rpassis** [comment]
Hey @swissdude can you please post your Podfile? Also if this is by any chance a toy project that you can share I’d greatly appreciate if you could attach that as well!
Thanks
Rog

**Comment by swissdude** [comment]
Hey @rpassis - Thanks for replying.
This is my podfile:

abstract_target 'MP' do
use_frameworks!
inhibit_all_warnings!
	platform :ios, '9.0'
	target 'MyProject' do
		pod 'GoogleAPIClientForREST/YouTube', '~> 1.2.1'
		pod 'GoogleSignIn', '~> 4.0'
		pod 'ObjectiveDropboxOfficial'
		pod 'VimeoNetworking', :path => './myProject/Submodules/VimeoNetworking'
		pod 'VimeoUpload', :path => './myProject/Submodules/VimeoUpload'
	end
end

Unfortunately, it's not a «toy» project ;) - and honestly way too big to attach it here...

**Comment by rpassis** [comment]
Hey @swissdude, thanks for all that info!

I'm not 100% sure what's going on with your project but I suspect you updated the `VimeoUpload` library to a version that depends on a new version of `VimeoNetworking`.

Have you tried updating `VimeoNetworking` to the latest version (4.0.0) as well?

FWIW I created a toy project for you have a look in the hopes that it might give you some clues as to what's going on - you can take a look at it here https://github.com/rpassis/VimeoUploaderSample.

I'd start with using the `Podfile` in the sample project above to see if it helps, and go from there.

Feel free to ping me back if you are still having issues.

Rog

**Comment by swissdude** [comment]
Hi @rpassis - thanks again for the reply!

The VimeoNetworking was also updated to version 4.0.0 while I was making the pod update.
So I guess this should be the latest version.
But I'll download your sample app and will try to compare it to mine... I'll let you know how it's going.

Thanks a ton for your effort! Greatly appreciated!

**Comment by rpassis** [comment]
Not a problem! And one more thing if you haven't done it yet - try cleaning your derived data folder.

**Comment by swissdude** [comment]
Hi @rpassis - It's working again.

I think that either my project-setup is totally screwed up or the pod-install/update functions don't work properly. In the end, I had to add every included framework to my scheme and build every framework manually before I could eventually build my own project.

Again, thanks a lot for your support!

**Comment by rpassis** [comment]
Great to hear, and feel free to reach out again if you need!
