### ISSUE TITLE
Cannot invoke 'type' with an argument list of type '(of: Descriptor)'

### ISSUE THREAD

**Issue by ideveloper1990** [vimeo/VimeoUpload#228]
#### Issue Summary
I am getting this error and not able to run project and showing this error from pod.

#### Reproduction Steps
I just clone folder to submodule folder and install pod and get this error.

see this error 
[http://prntscr.com/oyibo8](http://prntscr.com/oyibo8)

best

**Comment by rpassis** [comment]
Closed due to inactivity.
