### ISSUE TITLE
Cannot find a 'VimeoUpload' in cocoapods

### ISSUE THREAD

**Issue by escapeanaemia** [vimeo/VimeoUpload#235]
#### Issue Summary
Cannot find a 'VimeoUpload' in cocoapods

#### Reproduction Steps
Unable to find a specification for `VimeoUpload`
my cocoapods version is  `Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods.rb`
also I can't find it in https://cocoapods.org/

**Comment by rpassis** [comment]
Hi @escapeanaemia VimeoUpload is not available via the Cocoapods pod repo but you can install it by pointing directly to the github address and branch. 

```
pod “VimeoUpload”, :git => “https://github.com/Vimeo/VimeoUpload.git“, :branch => “develop”
```

I hope that helps!
Rog

**Comment by escapeanaemia** [comment]
Thank you!! your comment works :)
sadly I met new problem haha.. https://github.com/vimeo/VimeoUpload/issues/236
