### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by Ant-Adis** [vimeo/VimeoUpload#240]
#### Issue Summary
Can not install pod

#### Reproduction Steps
pod "VimeoUpload"
pod install

#### Expected Behavior
pod installation 

#### Actual Behavior
pod install error

Hi, I tried to install 
pod "VimeoUpload"

and I'm getting this error:

Analyzing dependencies
[!] Unable to find a specification for `VimeoUpload`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

I even tried this:
pod 'VimeoUpload'
pod 'VimeoNetworking', '~> 4.1.0'

but same error, can someone help? thanks

**Comment by rpassis** [comment]
Hi there,

`VimeoUpload` is not published as a pod on Cocoapods' trunk but you can consume directly from github with:

```ruby
pod 'VimeoUpload', :git => 'https://github.com/Vimeo/VimeoUpload.git', :branch => 'develop'
```

Good luck!
Rog
