### ISSUE TITLE
Get real url of video

### ISSUE THREAD

**Issue by Ant-Adis** [vimeo/VimeoUpload#242]
#### Issue Summary
I'm using pod from your develop branch and I'm using:

```
class NewVimeoUploader: VimeoUploader<UploadDescriptor>
{
    private static var APIVersionString: String
    {
        return "3.4"
    }

    static let sharedInstance = NewVimeoUploader(backgroundSessionIdentifier: "com.vimeo.upload", accessTokenProvider: { () -> String? in
        return "xxxxxxxxxxxx"
    }, apiVersion: APIVersionString)
}
```

The `UploadDescriptor` returns video object of `VIMVideo` and there is a property `link`, but he is not full URL of video just: `https://vimeo.com/xxxxxx`. I have a PRO version and I created a new token after upgrade? Can I get a real URL in response or do I need to use VimeoNetworking for fetching real URL?

**Comment by rpassis** [comment]
Hi there,
This library won't do that for you, you will need to use `VimeoNetworking` to fetch a download URL for your video.
Hope it helps.
Rog

**Comment by Ant-Adis** [comment]
Thanks
