### ISSUE TITLE
Unable to find a specification for `VimeoUpload`

### ISSUE THREAD

**Issue by theogscott** [vimeo/VimeoUpload#250]
#### Issue Summary
Trying to install the "VimeoUpload" using cocoapods, but I get the error Unable to find a specification for `VimeoUpload`

#### Reproduction Steps
I created a fresh new XCode project, use the command pod init, then added the line
pod "VimeoUpload" 
to the  PodFile, run pod install, but get the error: Unable to find a specification for `VimeoUpload`

I have run both:

pod repo update

and 

pod install --repo-update

but it did not resolve the issue.

See below copy of command and results as in the macOS Terminal

#### Expected Behavior
I expect the VimeoUpload pod to be install/added

#### Actual Behavior
What currently happens as a result of the reproduction steps?

##### 

tgs@HOTH vimeo upload % cat Podfile 
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'vimeo upload' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for vimeo upload
  pod "VimeoUpload"

  target 'vimeo uploadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'vimeo uploadUITests' do
    # Pods for testing
  end

end
tgs@HOTH vimeo upload % pod install
Analyzing dependencies
[!] Unable to find a specification for `VimeoUpload`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

tgs@HOTH vimeo upload % pod repo update
Updating spec repo `trunk`
tgs@HOTH vimeo upload % pod install
Analyzing dependencies
[!] Unable to find a specification for `VimeoUpload`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

tgs@HOTH vimeo upload % pod install --repo-update
Updating local specs repositories
Analyzing dependencies
[!] Unable to find a specification for `VimeoUpload`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

tgs@HOTH vimeo upload % ll Pods 
total 0
drwxr-xr-x  5 tgs  staff  160 17 Dec 13:18 .
drwxr-xr-x  8 tgs  staff  256 17 Dec 13:19 ..
drwxr-xr-x  2 tgs  staff   64 17 Dec 13:18 Headers
drwxr-xr-x  2 tgs  staff   64 17 Dec 13:18 Local Podspecs
drwxr-xr-x  2 tgs  staff   64 17 Dec 13:18 Target Support Files
tgs@HOTH vimeo upload %

**Comment by rpassis** [comment]
Hi there, and thanks for opening this issue!

VimeoUpload's is not currently published in the Cocoapods repository and it is unlikely to be in the near future. 

What this means is that you have to specify the repository and branch from which your Podfile should source it from ie

```
pod 'VimeoUpload', git: 'https://github.com/vimeo/VimeoUpload.git', branch: 'develop'
```

I hope it helps!

**Comment by theogscott** [comment]
Looks like `SWIFT_VERSION` is missing, which Swift compiler version are being used ?

pod install
Analyzing dependencies
Pre-downloading: `VimeoUpload` from `https://github.com/vimeo/VimeoUpload.git`, branch `develop`
Downloading dependencies
Installing VimeoNetworking (4.1.0)
Installing VimeoUpload (3.1.0)
[!] Unable to determine Swift version for the following pods:

 - `VimeoUpload` does not specify a Swift version and none of the targets (`vimeo upload`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by rpassis** [comment]
Hi there

Are you integrating with a target in your Podfile? Whatever target is consuming VimeoUpload should specify the SWIFT_VERSION in your own project build settings. 

For what it’s worth we use Swift 5 on VimeoUpload and any new Xcode project you create should set that version as the default.

**Comment by DevGirisankar** [comment]
> pod 'VimeoUpload', git: 'https://github.com/vimeo/VimeoUpload.git', branch: 'develop'

When can we expect the release? 
Can I use dev branch checkout in my release ready project? which will be released next month.

**Comment by rpassis** [comment]
Hi there yes you can use the version in the develop branch on your project. We have no plans of releasing this via Cocoapods in the near future.
