### ISSUE TITLE
A crash is happening every single time (upon applying video settings)

### ISSUE THREAD

**Issue by miraclebg** [vimeo/VimeoUpload#78]
I am in no way into Swift :) - old school objective c dev and this is why i am posting this - it's probably a silly issue.

Checked out the latest version - and:

- ran it under XCode 7.3
- uploaded a video to a 9.3 simulator
- tried to upload with the demo app you have created
- i see progress in the console reaching 1.00
- then i tap 'Upload'
- app crashes

The video actually gets uploaded - but the settings (title, description) do not get updated - this is where the app crashes.

Attaching two screenshots - one stopped at the breakpoint before the crash and one after.

It seems the video is nil - but beats me why :) I can only logically guess what is happening by looking at the swift code but that is where my super powers end :)
![screen shot 2016-03-30 at 17 33 06](https://cloud.githubusercontent.com/assets/126405/14145827/fa9ae6a8-f69d-11e5-9562-dd98f4f42ee8.png)
![screen shot 2016-03-30 at 17 33 14](https://cloud.githubusercontent.com/assets/126405/14145828/fac5800c-f69d-11e5-9583-c9a6802d04f2.png)

**Comment by alfiehanssen** [comment]
@miraclebg My guess is that you're using the not-yet-public upload API. Check out the README for info on the existing public API affectionately called "OldUpload" and the new still-private API called "NewUpload". 

https://github.com/vimeo/VimeoUpload#old-upload-new-upload

We hope to make NewUpload public a little later this year. For now, the library supports it and the code that supports it is public, but third party developers cannot yet use it (the video object will be nil, as well as a few other things).

**Comment by miraclebg** [comment]
@alfiehanssen You are probably right.

I moved to UploadOld and things are working now.

I also had to do some changes to the Swift code as i need to use it from our primary codebase which is in Objective-C (generic types are not allowed in objc).

But i've just been able to successfully upload so i am pretty happy ;)

Thanks!

**Comment by alfiehanssen** [comment]
That's great, glad it's uploading :) 

Closing this issue as it seems to be fixed, 

Keep us posted,

**Comment by VivekGoswami** [comment]
Hello, I am trying to upload video from demo app, and i still getting above issue in both version Oldupload and newupload, what should i do for resolve that. @alfiehanssen

**Comment by VivekGoswami** [comment]
Crashes issue solved by unwrapping value of videoUri, but process of upload is endless. any solution for that @alfiehanssen
