### ISSUE TITLE
Cannot able to upload a video to vimeo using VimeoUpload-iOS application

### ISSUE THREAD

**Issue by krishna-inexgen** [vimeo/VimeoUpload#83]
#### Issue Summary
A brief but thorough description of the issue.

#### Reproduction Steps
Detailed steps to reproduce the issue.

#### Expected Behavior
What do you expect to happen as a result of the reproduction steps?

#### Actual Behavior
What currently happens as a result of the reproduction steps?

**Comment by kevinzetterstrom** [comment]
Hi Krishna, can you confirm you have upload access? If you go to your application settings in the API dashboard (https://developer.vimeo.com/apps), you can determine if you have been given access. Within the "Details" tab look under the section "Upload Access". If you do not have it, it will say "None - Request Upload Access". Click on that link in order to request upload access with the Vimeo API.

**Comment by alfiehanssen** [comment]
Thanks @kevinzetterstrom, 

Just added this to the README on branch v0.9

**Comment by alfiehanssen** [comment]
@krishna-inexgen please let us know if this resolves the issue

**Comment by iamabhiee** [comment]
faced the same its crashing while using new video upload while old video upload is working fine, can you also give example of integrating new sdk with objective-c project?

**Comment by alfiehanssen** [comment]
"New upload" is still private and will not work for the general public, as explained in the readme. It will be made available to the general public later this year.

We can post an objective c same soon. Realistically though it probably won't be for a few weeks.

On Apr 22, 2016, at 3:07 AM, Abhishek Sheth <notifications@github.com<mailto:notifications@github.com>> wrote:


faced the same its crashing while using new video upload while old video upload is working fine, can you also give example of integrating new sdk with objective-c project?

**Comment by alfiehanssen** [comment]
@iamabhiee 

Circling back on this. We're most likely not going to post an Objective-C sample project. Swift and Objective-C interoperability is robust and well-documented by Apple and the dev community. Should be pretty straightforward to integrate this Swift library into an Objc project. Let us know if you have issues doing so and we'll try to help out.
