### ISSUE TITLE
How to get the video details(uploaded from iOS App using Vimeo SDK) once its uploaded in Vimeo server? Or Which API should we used to get the details of an uploaded Video from an ios app?

### ISSUE THREAD

**Issue by vasanthakumars** [vimeo/VimeoUpload#84]
#### Issue Summary
A brief but thorough description of the issue.

#### Reproduction Steps
Detailed steps to reproduce the issue.

#### Expected Behavior
What do you expect to happen as a result of the reproduction steps?

#### Actual Behavior
What currently happens as a result of the reproduction steps?

**Comment by alfiehanssen** [comment]
@vasanthakumars Great question, thanks for filing the issue. 

You can get the video object associated with the file you just uploaded in two ways: 

1. The video object is returned in the "activate" response. This request is made by the `OldUploadDescriptor` as soon as the file upload completes. Check out the `.Activate` case [here](https://github.com/vimeo/VimeoUpload/blob/v0.9/VimeoUpload/Upload/Descriptor%20System/Old%20Upload/OldUploadDescriptor.swift#L227). Actually, now that I'm writing this, the video object might actually come back in the `.Settings` response. Either way the example of how to do this is at the same link above. 

2. You can also request a video object separately from anything related to the upload flow by making a `GET` request to the video's uri. The `VideoOperation` class contains an [example of this](https://github.com/vimeo/VimeoUpload/blob/v0.9/VimeoUpload/Upload/Operations/Async/VideoOperation.swift). 

You can also access the `video.uri` and entire video object on the descriptor itself (once the upload is complete). Look [here](https://github.com/vimeo/VimeoUpload/blob/v0.9/VimeoUpload/Upload/Descriptor%20System/Old%20Upload/OldUploadDescriptor.swift#L38).

Let us know if you have other questions.

**Comment by coneits** [comment]
I have checked your comment, but still can't get the video id like "https://vimeo.com/164824324".
looks like "https://1511928471.cloud.vimeo.com/upload?ticket_id=59821e7edc5840322fc360b63d9414c7_45995664&video_file_id=520623428&signature=ec0ce3b5852802957cc1e19c2cccbfa8&v6=1".
I have also checked the .Active state... but no luck.
can you help me?
