### ISSUE TITLE
I couldn't add meta data to video such as title, description, etc on the example project. They are always empty after upload video. Pls let us know what the reason is. Thanks

### ISSUE THREAD

**Issue by coneits** [vimeo/VimeoUpload#87]
#### Issue Summary
A brief but thorough description of the issue.

#### Reproduction Steps
Detailed steps to reproduce the issue.

#### Expected Behavior
What do you expect to happen as a result of the reproduction steps?

#### Actual Behavior
What currently happens as a result of the reproduction steps?

**Comment by alfiehanssen** [comment]
@coneits Please provide more specific information. Without specific information it's tough for us to help you resolve the issue. What debugging have you done? What does your code look like?

**Comment by alfiehanssen** [comment]
Also, @coneits, please use the pull request template instead of including the entirety of your explanation in the pull request title.

**Comment by coneits** [comment]
hello, @alfiehanssen 
Thank you for your help.
I have just tested the sample example code(VimeoUpload-iOS-OldUpload), but after upload the video from my iphone, the video hasn't got the title and description on the my account of vimeo.
it shows "untitiled" only, and empty description.

could you let us know about that please?
thanks

**Comment by coneits** [comment]
could you please let me know why the title and descriptions were not added to the video on sample example project(ios-old)?

**Comment by coneits** [comment]
is that pending issue that isn't solved yet?

**Comment by alfiehanssen** [comment]
@coneits, the "old upload" demo is definitely working when I drop a valid auth token in. Which makes me think there's something up with your token. How are you generating your auth token? Do you have the proper scopes? You should at a minimum have the "public private create edit upload" scopes in place. 

Available scopes are shown here: 

![scopes](https://cloud.githubusercontent.com/assets/991059/14936112/ea9692cc-0eb5-11e6-8081-6201357aa023.png)

**Comment by alfiehanssen** [comment]
@coneits What debugging have you done? I suggest setting some break points where the "settings" request completion is handled and checking the status code etc. Also, your UploadDescriptor's error property will be set if the settings request fails.
