### ISSUE TITLE
How to get Video Details From Vimeo iOS SDK Once Uploaded?

### ISSUE THREAD

**Issue by coneits** [vimeo/VimeoUpload#88]
I have checked your comment, but still can't get the video id like "https://vimeo.com/164824324" after uploading video.
looks like "https://1511928471.cloud.vimeo.com/upload?ticket_id=59821e7edc5840322fc360b63d9414c7_45995664&video_file_id=520623428&signature=ec0ce3b5852802957cc1e19c2cccbfa8&v6=1".
I have also checked the .Active state... but no luck.
can you help me?

**Comment by coneits** [comment]
how to get the video url that i have just uploaded like "https://vimeo.com/164824324" please?
is that impossible to get that link on current OldUploadDescriptor?
if you could let me know the result as soon as possible, it will be helpful.

**Comment by coneits** [comment]
In fact, I want to get full video object after upload the video, but when I debugging at .Activate state, the video(VIMVideo?) is always nil.
would you help me please now?

**Comment by coneits** [comment]
I have found the reason and solved the issue. Thanks.

**Comment by mehuls1013** [comment]
Hello @coneits 

How you got the video_id after successful upload video?

Can you please help?

**Comment by ErAshu** [comment]
Hello @coneits 

How you got the video_id after successful upload video?

Please help?
