### ISSUE TITLE
How to upload the recording video to vimeo directly with Old Upload code? Thanks.

### ISSUE THREAD

**Issue by coneits** [vimeo/VimeoUpload#89]
#### Issue Summary
A brief but thorough description of the issue.

#### Reproduction Steps
Detailed steps to reproduce the issue.

#### Expected Behavior
What do you expect to happen as a result of the reproduction steps?

#### Actual Behavior
What currently happens as a result of the reproduction steps?

**Comment by alfiehanssen** [comment]
VimeoUpload does not support this functionality. You'll have to build that custom.
