### ISSUE TITLE
How to get video thumbnail after upload the video? When checking the video object, it doesn't have the thumbnail image on it. Could you check this please?

### ISSUE THREAD

**Issue by coneits** [vimeo/VimeoUpload#91]
#### Issue Summary
A brief but thorough description of the issue.

#### Reproduction Steps
Detailed steps to reproduce the issue.

#### Expected Behavior
What do you expect to happen as a result of the reproduction steps?

#### Actual Behavior
What currently happens as a result of the reproduction steps?

**Comment by alfiehanssen** [comment]
Please read the documentation on the Vimeo API: https://developer.vimeo.com/api
