### ISSUE TITLE
Can't use with Objective-C project

### ISSUE THREAD

**Issue by iamabhiee** [vimeo/VimeoUpload#97]
#### Issue Summary

I have added files all swift files in my Objective-C project from VimeoUpload folder
I have added #import “-Swift.h” in my project
To subclass VimeoUpload, I am adding @objc in the class definition and it gives me following error

"Generic subclasses of '@objc' classes cannot have an explicit '@objc' attribute because they are not directly visible from Objective-C.”

That is because VimeoUpload is generic class, Is there any straightforward way to use this with Objective-C project

**Comment by ErAshu** [comment]
Any update?? @iamabhiee how can i integrate with objective c?
